### ISSUE TITLE
SpringBoot-2.2.2 is not working, throw java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by JobsZCQ** [spring-projects-experimental/spring-boot-thin-launcher#125]
using thin 1.0.22.RELEASE, throw follow execption
```java
[2019/12/20 16:27]BruceZCQ@JobszSPro:learning-spring-boot-mybatis-module master$ java -jar ./web/target/web-0.0.1-SNAPSHOT.jar
Exception in thread "main" java.lang.ClassNotFoundException: org.springframework.boot.loader.thin.ThinJarLauncher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:139)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
```

**Comment by JobsZCQ** [comment]
I change to 1.0.23.RELEASE ，workded
