### ISSUE TITLE
Thinlauncher does not download from repos configured in pom.xml

### ISSUE THREAD

**Issue by horschi** [spring-projects-experimental/spring-boot-thin-launcher#152]
In my project I am using org.scijava:scripting-jython:jar:1.0.0, which can be found in repo https://maven.imagej.net/content/repositories/releases/. My local maven resolves this library just fine, but thin-launcher is not able to download it. Thin-launcher reports that it cannot download the library from the spring-snapshots repo.

I would assume that thin-launcher should download libraries from the repositories configured in my maven-pom, which for me it does not seem to do.

My repo definition in my pom.xml:
```
	<repositories>
		<repository>
			<id>Central</id>
			<url>https://repo.maven.apache.org/maven2/</url>
		</repository>
		<repository>
			<id>imagej</id>
			<name>imagej</name>
			<url>https://maven.imagej.net/content/repositories/releases/</url>
		</repository>
		<repository>
			<id>snapshots-repo</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>	
```

Thing-launcher exception:
```
 Exception in thread "main" java.lang.reflect.InvocationTargetException
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:140)
         at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
 Caused by: java.lang.IllegalStateException: hidden.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.scijava:scripting-jython:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
         at org.springframework.boot.loader.thin.DependencyResolver.collectNonTransitive(DependencyResolver.java:613)
         at org.springframework.boot.loader.thin.DependencyResolver.aetherDependencies(DependencyResolver.java:256)
         at org.springframework.boot.loader.thin.DependencyResolver.dependencies(DependencyResolver.java:204)
         at org.springframework.boot.loader.thin.PathResolver.extract(PathResolver.java:214)
         at org.springframework.boot.loader.thin.PathResolver.resolve(PathResolver.java:101)
         at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchives(ThinJarLauncher.java:355)
         at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
         at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:193)
         at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:140)
         ... 6 more
 Caused by: hidden.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.scijava:scripting-jython:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
         at hidden.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
         at hidden.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
         at hidden.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifacts(DefaultRepositorySystem.java:302)
         at org.springframework.boot.loader.thin.DependencyResolver.collectNonTransitive(DependencyResolver.java:608)
         ... 14 more
 Caused by: hidden.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.scijava:scripting-jython:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
         at hidden.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
         at hidden.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
         at hidden.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
         at hidden.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
         at hidden.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
         at hidden.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
         at hidden.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
         ... 17 more

```
If I download that library manually, then it works fine. All other dependencies are being downloaded just fine, I assume because they are available in the spring-snapshots repo.

**Comment by horschi** [comment]
This ticket is a duplicate of #153
