### ISSUE TITLE
Does not download libraries from repo configured in pom.xml

### ISSUE THREAD

**Issue by horschi** [spring-projects-experimental/spring-boot-thin-launcher#153]
In my project I am using org.scijava:scripting-jython:jar:1.0.0, which can be found in repo https://maven.imagej.net/content/repositories/releases/. My local maven resolves this library just fine, but thin-launcher is not able to download it. Thin-launcher reports that it cannot download the library from the spring-snapshots repo.

I would assume that thin-launcher should download libraries from the repositories configured in my maven-pom, which for me it does not seem to do.

My repo definition in my pom.xml:
```
	<repositories>
		<repository>
			<id>Central</id>
			<url>https://repo.maven.apache.org/maven2/</url>
		</repository>
		<repository>
			<id>imagej</id>
			<name>imagej</name>
			<url>https://maven.imagej.net/content/repositories/releases/</url>
		</repository>
		<repository>
			<id>snapshots-repo</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>	
```

Thin-launcher exception:
```
 Exception in thread "main" java.lang.reflect.InvocationTargetException
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:140)
         at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
 Caused by: java.lang.IllegalStateException: hidden.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.scijava:scripting-jython:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
         at org.springframework.boot.loader.thin.DependencyResolver.collectNonTransitive(DependencyResolver.java:613)
         at org.springframework.boot.loader.thin.DependencyResolver.aetherDependencies(DependencyResolver.java:256)
         at org.springframework.boot.loader.thin.DependencyResolver.dependencies(DependencyResolver.java:204)
         at org.springframework.boot.loader.thin.PathResolver.extract(PathResolver.java:214)
         at org.springframework.boot.loader.thin.PathResolver.resolve(PathResolver.java:101)
         at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchives(ThinJarLauncher.java:355)
         at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
         at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:193)
         at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:140)
         ... 6 more
 Caused by: hidden.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.scijava:scripting-jython:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
         at hidden.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
         at hidden.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
         at hidden.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifacts(DefaultRepositorySystem.java:302)
         at org.springframework.boot.loader.thin.DependencyResolver.collectNonTransitive(DependencyResolver.java:608)
         ... 14 more
 Caused by: hidden.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.scijava:scripting-jython:jar:1.0.0 in spring-snapshots (https://repo.spring.io/libs-snapshot)
         at hidden.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
         at hidden.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
         at hidden.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
         at hidden.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
         at hidden.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
         at hidden.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
         at hidden.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
         ... 17 more

```
If I download that library manually, then it works fine. All other dependencies are being downloaded just fine, I assume because they are available in the spring-snapshots repo.

I am using thin-launcher 1.0.25.RELEASE.

**Comment by dsyer** [comment]
How about trying 1.0.26?

**Comment by TimoZikeli** [comment]
Unfortunately, it still does not work for me with gradle:

```
dependencies {
    compile 'com.github.kenglxn.qrgen:javase:2.6.0'
}

repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
    mavenLocal()
    jcenter()
}
```

The dependency is not found when starting the thin jar and the pom.xml in the Jar does not contain any repository URLs. Additionally, I have a `compile project(:module)` dependency which is not included in the thin jar either.

It would be great if this was fixed, thanks!

**Comment by dsyer** [comment]
Gradle support is a bit of a basket case at the minute, and whether or not the above works is highly dependent on many factors, principally the version of Gradle you use. Hopefully we can do something about that soon, and help is more than welcome whenever you have some cycles.

However, the title of this issue only mentions a `pom.xml` so I assume that's a different problem? If so then please open a separate issue or follow one of the existing ones (like #50).

**Comment by horschi** [comment]
@dsyer : I'd be glad to give more detailed steps, but I do not know where to start. 

Where in my final jar file should the repo information be? Where during runtime is thin-launcher reading the repository URL?

**Comment by dsyer** [comment]
> Where in my final jar file should the repo information be?

In the pom, in the normal place. You are building with Maven right?

> Where during runtime is thin-launcher reading the repository URL?

You mean "where" or "when"? When, is on start up when it is computing the classpath. Where, is from the pom.xml.

Steps to reproduce would include ideally a sample app and a README with a list of commands to run.

**Comment by horschi** [comment]
@dsyer : Aha, then I think I understand the issue now: My repositories are configured in one of the parent projects, not the application project or its dependencies. 

In my application project pom I have:
	<parent>
		<groupId>com.mydummy</groupId>
		<artifactId>parent</artifactId>
		<version>0.0.1</version>
		<relativePath>../parent</relativePath>
	</parent>
And in this parent there is the repository configuration. But this configuration is not used by thing-launcher I think.

I will test to be sure ...

**Comment by dsyer** [comment]
The parent would have to be deployed and downloadable, but it will be used at runtime.

**Comment by horschi** [comment]
@dsyer Yes, but my parent is not downloadable. So thats the problem. But if I put the repository in my dependency, it should work. At least I can see my dependency poms in the JAR file.

**Comment by horschi** [comment]
@dsyer : So I just tested and of course it worked flawlessly.

Would it perhaps an idea to include the repo URLs in the thin.properties to avoid such issues in the future?

**Comment by dsyer** [comment]
That would be a new feature. I'm not sure I'd care for it (you have to duplicate the information in properties and XML). Why not just install the parent in a Maven repo?

**Comment by horschi** [comment]
@dsyer I'm fine, I can live without it.

Thanks for your help!
