### ISSUE TITLE
multi module sample run failed

### ISSUE THREAD

**Issue by Kylin824** [spring-projects-experimental/spring-boot-thin-launcher#179]
Hi Dave，I try to package the code from "spring-projects-experimental/spring-boot-thin-launcher/samples/multi/" and use "jar -jar application-0.0.1-SNAPSHOT.jar"  after package. However, i got the error msg as follows: 

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:139)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
Caused by: java.lang.IllegalStateException: Cannot build model
        at org.springframework.boot.loader.thin.DependencyResolver.dependencies(DependencyResolver.java:252)
        at org.springframework.boot.loader.thin.PathResolver.extract(PathResolver.java:259)
        at org.springframework.boot.loader.thin.PathResolver.resolve(PathResolver.java:105)
        at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchives(ThinJarLauncher.java:369)
        at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchives(ThinJarLauncher.java:352)
        at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchivesIterator(ThinJarLauncher.java:200)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:55)
        at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:195)
        at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:141)
        ... 6 more
Caused by: hidden.org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model for com.example:application:[unknown-version]
[FATAL] Non-resolvable parent POM for com.example:application:[unknown-version]: Could not find artifact com.example:multi:pom:0.0.1-SNAPSHOT in spring-snapshots (https://repo.spring.io/libs-snapshot) @ line 9, column 10
 for project com.example:application:[unknown-version]
        at hidden.org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:165)
        at hidden.org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:123)
        at org.springframework.boot.loader.thin.DependencyResolver.dependencies(DependencyResolver.java:212)
        ... 14 more

I'm not sure whether the running statement is missing some parameters, resulting in a lack of correct POM dependencies. Hope to get your reply. Thanks!

**Comment by chenjun19950315** [comment]
how did you solve this problem

**Comment by chenjun19950315** [comment]
How did you solve this problem, I have this problem too

**Comment by chenjun19950315** [comment]
怎么解决的，我也有这个问题

**Comment by chenjun19950315** [comment]
How did you solve it, I have this problem too

**Comment by chenjun19950315** [comment]
How did you solve it, I have this problem too
