### ISSUE TITLE
Can not download full file when using  -Dthin.repo="http://maven.aliyun.com/nexus/content/groups/public/"

### ISSUE THREAD

**Issue by zzy444626905** [spring-projects-experimental/spring-boot-thin-launcher#183]
[root@app ~]# java -Dthin.debug=true -Dthin.repo="http://maven.aliyun.com/nexus/content/groups/public/" -jar jar-exe-1.0-SNAPSHOT.jar
Downloading launcher from: http://maven.aliyun.com/nexus/content/groups/public/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.28.RELEASE/spring-boot-thin-launcher-1.0.28.RELEASE-exec.jar
Using launcher: /root/.m2/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.28.RELEASE/spring-boot-thin-launcher-1.0.28.RELEASE-exec.jar
Exception in thread "main" java.lang.ClassNotFoundException: org.springframework.boot.loader.thin.ThinJarLauncher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:138)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)

**Comment by zzy444626905** [comment]
the method downloadFromUrl can not redirect

**Comment by zzy444626905** [comment]
the method downloadFromUrl can not redirect

**Comment by zzy444626905** [comment]
it's done by myself... ths

java -Dthin.debug=true -Dthin.repo="https://maven.aliyun.com/repository/central/" -jar jar-exe-1.0-SNAPSHOT.jar
