### ISSUE TITLE
Default Repository currently not working. Change default thin.repo to maven central, if this isn't just temporary?

### ISSUE THREAD

**Issue by 125m125** [spring-projects-experimental/spring-boot-thin-launcher#192]
Executing a freshly built thin jar currently provides me the following exception:
```
> java -jar -Dthin.debug=true target/example-0.0.1-SNAPSHOT.jar
Downloading launcher from: https://repo.spring.io/libs-snapshot/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.28.RELEASE/spring-boot-thin-launcher-1.0.28.RELEASE-exec.jar
Failed to download: https://repo.spring.io/libs-snapshot/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.28.RELEASE/spring-boot-thin-launcher-1.0.28.RELEASE-exec.jar
Exception in thread "main" java.lang.IllegalStateException: Cannot locate launcher: .../.m2/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.28.RELEASE/spring-boot-thin-launcher-1.0.28.RELEASE-exec.jar
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:131)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
```
When manually opening the URL from where it is trying to download the exec.jar, I am asked for login details. I guess it could be connected to https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020 ?

Starting it with a modified thin.repo works:
```
> java -jar -Dthin.debug=true -Dthin.repo=https://repo1.maven.org/maven2/ target/example-0.0.1-SNAPSHOT.jar
Downloading launcher from: https://repo1.maven.org/maven2/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.28.RELEASE/spring-boot-thin-launcher-1.0.28.RELEASE-exec.jar
Using launcher: .../.m2/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.28.RELEASE/spring-boot-thin-launcher-1.0.28.RELEASE-exec.jar
Jan 13, 2023 8:06:53 PM org.springframework.boot.loader.thin.ThinJarLauncher launch
INFORMATION: Version: 1.0.28.RELEASE
...
```

In my eyes the default for thin.repo should point to maven central or the Getting Started should at least indicate that you (might) need to change thin.repo to a public (or your own) repository?

Maven configuration (in case I did something wrong):
```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot.experimental</groupId>
			<artifactId>spring-boot-thin-layout</artifactId>
			<version>1.0.28.RELEASE</version>
		</dependency>
	</dependencies>
	<configuration>
		<executable>true</executable>
		<excludes>
			<exclude>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
			</exclude>
		</excludes>
	</configuration>
</plugin>
```

**Comment by dsyer** [comment]
Should be fixed in 1.0.29.RELEASE. There are some changes happening in repo.spring.io.
