### ISSUE TITLE
Spring boot thin launcher jar not found

### ISSUE THREAD

**Issue by sfetzel** [spring-projects-experimental/spring-boot-thin-launcher#196]
The following exception is raised when launching a simple demo project:
```
C:\Users\simon\Downloads\demo\demo>java -Dthin.debug=true -jar target\demo-0.0.1-SNAPSHOT.jar
Downloading launcher from: https://repo.spring.io/snapshot/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.29.RELEASE/spring-boot-thin-launcher-1.0.29.RELEASE-exec.jar
Failed to download: https://repo.spring.io/snapshot/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.29.RELEASE/spring-boot-thin-launcher-1.0.29.RELEASE-exec.jar
Exception in thread "main" java.lang.IllegalStateException: Cannot locate launcher: C:\Users\simon/.m2/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.29.RELEASE/spring-boot-thin-launcher-1.0.29.RELEASE-exec.jar
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:131)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)

C:\Users\simon\Downloads\demo\demo>
```

It seems that https://repo.spring.io/snapshot/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.29.RELEASE/spring-boot-thin-launcher-1.0.29.RELEASE-exec.jar is unavailable.

Reproduction steps:
- Clean local m2 repository.
- Go to Spring initalizr.
- Create a new Maven project.
- Apply configuration from [Getting Started](https://github.com/spring-projects-experimental/spring-boot-thin-launcher#getting-started)
- Create package using maven.
- Start the thin jar

**Comment by dsyer** [comment]
Should be fixed in 1.0.30
